# Generated by Django 5.0.6 on 2026-07-03 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('purpose', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=16)),
                ('required_votes', models.IntegerField(default=3)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('occurred_on', models.DateField(db_index=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='core.business')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='core.expensecategory')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос согласования',
                'verbose_name_plural': 'Запросы согласования',
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(choices=[('approve', 'Добро'), ('reject', 'Нет')], max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_votes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='approvals.approvalrequest')),
            ],
            options={
                'verbose_name': 'Голос согласования',
                'verbose_name_plural': 'Голоса согласования',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['business', 'status'], name='approvals_a_busines_60934a_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'occurred_on'], name='approvals_a_status_bcecd2_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='approvals_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='approvalvote',
            constraint=models.UniqueConstraint(fields=('request', 'owner'), name='uq_approval_vote_owner'),
        ),
    ]
