# Generated by Django 5.0.6 on 2026-07-03 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('base_fixed', models.DecimalField(decimal_places=2, default=0, help_text='Базовый фикс схемы', max_digits=14)),
                ('rules', models.JSONField(default=list, help_text='Список правил бонуса')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Схема ЗП',
                'verbose_name_plural': 'Схемы ЗП',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('salary_type', models.CharField(choices=[('object', 'Объектный'), ('admin', 'Административный')], default='object', max_length=16)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, help_text='Оклад', max_digits=14)),
                ('is_salesperson', models.BooleanField(default=False, help_text='Продажник (ЗРП-03)')),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.business')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='payroll.payrollscheme')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('calculated', 'Рассчитана'), ('approved', 'Утверждена'), ('paid', 'Выплачена')], db_index=True, default='draft', max_length=16)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Расчёт ЗП',
                'verbose_name_plural': 'Расчёты ЗП',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('details', models.JSONField(default=dict, help_text='Разбивка бонуса')),
                ('metrics', models.JSONField(default=dict, help_text='Входные метрики расчёта')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_items', to='payroll.employee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payrollrun')),
            ],
            options={
                'verbose_name': 'Строка ЗП',
                'verbose_name_plural': 'Строки ЗП',
                'ordering': ['run', 'employee__full_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='uq_payroll_run_period'),
        ),
        migrations.AddIndex(
            model_name='payrollitem',
            index=models.Index(fields=['run', 'employee'], name='payroll_pay_run_id_838e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['business', 'is_active'], name='payroll_emp_busines_7d276f_idx'),
        ),
    ]
