# Generated by Django 5.0.6 on 2026-07-03 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], db_index=True, max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод')], max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('rejected', 'Отклонён'), ('void', 'Аннулирован')], db_index=True, default='pending', max_length=16)),
                ('occurred_on', models.DateField(db_index=True)),
                ('counterparty', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('is_barter', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.business')),
                ('category', models.ForeignKey(blank=True, help_text='Статья — обязательна для расходов (ФНС-02)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.expensecategory')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_transactions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.siteobject')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-occurred_on', '-created_at'],
                'indexes': [models.Index(fields=['business', 'kind', 'status'], name='finance_tra_busines_65d265_idx'), models.Index(fields=['occurred_on', 'business'], name='finance_tra_occurre_d65b97_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='finance_tx_amount_positive'),
        ),
    ]
