# Generated by Django 5.0.6 on 2026-07-04 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='checked_by',
            field=models.ForeignKey(blank=True, help_text='Бухгалтер, проверивший операцию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_disbursement',
            field=models.BooleanField(default=False, help_text='Выдача денег руководителю'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_manager',
            field=models.ForeignKey(blank=True, help_text='Руководитель — получатель выдачи', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_disbursements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, help_text='Владелец, подтвердивший крупную операцию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(help_text='Менеджер, создавший операцию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'Ожидает проверки бухгалтера'), ('awaiting_owner', 'Ожидает подтверждения владельца'), ('confirmed', 'Подтверждён'), ('rejected', 'Отклонён'), ('void', 'Аннулирован')], db_index=True, default='pending', max_length=16),
        ),
    ]
