# Generated by Django 5.0.6 on 2026-07-04 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('receipt', 'Чек'), ('invoice', 'Счёт'), ('contract', 'Договор'), ('waybill', 'Накладная'), ('other', 'Прочее')], db_index=True, default='other', max_length=16)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документ операции',
                'verbose_name_plural': 'Документы операций',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='documents_o_content_0d1ef4_idx')],
            },
        ),
    ]
