# Generated by Django 5.0.6 on 2026-07-03 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('occurred_on', models.DateField(db_index=True)),
                ('is_barter', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Ожидает одобрения'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], db_index=True, default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transfers', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='core.business')),
                ('to_business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='core.business')),
            ],
            options={
                'verbose_name': 'Передача',
                'verbose_name_plural': 'Передачи',
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('partially_settled', 'Частично закрыт'), ('settled', 'Закрыт')], db_index=True, default='open', max_length=20)),
                ('is_barter', models.BooleanField(default=False)),
                ('occurred_on', models.DateField(db_index=True)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts_as_creditor', to='core.business')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts_as_debtor', to='core.business')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_transfer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt', to='settlements.transfer')),
            ],
            options={
                'verbose_name': 'Долг',
                'verbose_name_plural': 'Долги',
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('netting', 'Взаимозачёт'), ('repayment', 'Возврат'), ('barter', 'Бартер')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('occurred_on', models.DateField(db_index=True)),
                ('counter_debt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_settlements', to='settlements.debt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settlements', to=settings.AUTH_USER_MODEL)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='settlements.debt')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Закрытие долга',
                'verbose_name_plural': 'Закрытия долгов',
                'ordering': ['-occurred_on', '-created_at'],
                'indexes': [models.Index(fields=['debt', 'kind'], name='settlements_debt_id_34e2fa_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='settlements_settlement_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['from_business', 'to_business', 'status'], name='settlements_from_bu_b8dec2_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['occurred_on', 'status'], name='settlements_occurre_eb070c_idx'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='settlements_transfer_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(check=models.Q(('from_business', models.F('to_business')), _negated=True), name='settlements_transfer_distinct_businesses'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['debtor', 'creditor', 'status'], name='settlements_debtor__d7ba6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='settlements_debt_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(check=models.Q(('outstanding__gte', 0)), name='settlements_debt_outstanding_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(check=models.Q(('debtor', models.F('creditor')), _negated=True), name='settlements_debt_distinct_businesses'),
        ),
    ]
