# Generated by Django 5.0.6 on 2026-07-04 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_idempotencykey_result_pk'),
        ('settlements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('receivable', 'Нам должны'), ('payable', 'Мы должны')], db_index=True, max_length=16)),
                ('counterparty', models.CharField(help_text='Внешний контрагент', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('partially_settled', 'Частично закрыт'), ('settled', 'Закрыт')], db_index=True, default='open', max_length=20)),
                ('occurred_on', models.DateField(db_index=True)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_debts', to='core.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_external_debts', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Внешняя задолженность',
                'verbose_name_plural': 'Внешние задолженности',
                'ordering': ['-occurred_on', '-created_at'],
                'indexes': [models.Index(fields=['direction', 'status'], name='settlements_directi_e5c41a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='externaldebt',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='settlements_extdebt_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='externaldebt',
            constraint=models.CheckConstraint(check=models.Q(('outstanding__gte', 0)), name='settlements_extdebt_outstanding_nonneg'),
        ),
    ]
