# Generated by Django 5.0.6 on 2026-07-03 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(help_text='Стабильный машинный код кассы', unique=True)),
                ('turnover_limit', models.DecimalField(decimal_places=2, default=0, help_text='Лимит оборота за месяц; 0 = без лимита (КАС-03)', max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to='core.business')),
                ('responsible', models.ManyToManyField(blank=True, help_text='Кассиры, ответственные за кассу', related_name='cash_registers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Кассы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], db_index=True, max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод')], max_length=16)),
                ('occurred_on', models.DateField(db_index=True)),
                ('counterparty', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_operations', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('finance_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_operation', to='finance.transaction')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='cash.cashregister')),
            ],
            options={
                'verbose_name': 'Кассовая операция',
                'verbose_name_plural': 'Кассовые операции',
                'ordering': ['-occurred_on', '-created_at'],
                'indexes': [models.Index(fields=['register', 'kind'], name='cash_cashop_registe_c6f3d4_idx'), models.Index(fields=['occurred_on', 'register'], name='cash_cashop_occurre_0fada0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cashoperation',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='cash_operation_amount_positive'),
        ),
    ]
